sudo: required
dist: xenial

services:
  - docker

before_script:
  - sudo apt-get purge -y cmake
  - cmake --version
  - sudo bash scripts/set-up-system.sh
  - scripts/set-up-python.sh --python=python3
  - source .venv/bin/activate
  - export CC=`which gcc-5`
  - export CXX=`which g++-5`
  - scripts/set-up-conan.sh
  - ./fips set config linux-make-debug
  - ./fips gen

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - ./fips make unit_test_coverage
  - ./fips make integration_tests
