sudo: required
dist: focal

services:
  - docker

before_script:
  - sudo rm -rf /usr/local/cmake-*
  - sudo bash scripts/set-up-system.sh
  - cmake --version
  - docker version
  - scripts/set-up-python.sh --python=python3
  - source .venv/bin/activate
  - export CC=`which gcc`
  - export CXX=`which g++`
  - scripts/set-up-conan.sh
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
  - make -j unit_test_coverage
  - make -j integration_tests
