name: Clang

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CRADLE_THINKNODE_API_TOKEN: ${{ secrets.CRADLE_THINKNODE_API_TOKEN }}
  CRADLE_THINKNODE_DOCKER_AUTH: ${{ secrets.CRADLE_THINKNODE_DOCKER_AUTH }}

jobs:

  clang:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
        key: ${{runner.os}}-Clang-14-${{matrix.config}}

    - name: Install
      run: |
        sudo apt install lcov ocaml-nox
        sudo pip3 install virtualenv
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 14

    - name: Configure
      run: |
        export CC=`which clang-14`
        export CXX=`which clang++-14`
        ${CXX} --version
        scripts/set-up-python.sh --python=python3
        source .venv/bin/activate
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} .

    - name: Build & Test
      run: |
        python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
        cmake --build build --config ${{matrix.config}} --target all_unit_tests -j4
        source .venv/bin/activate
        pip3 install -e python
        cmake --build build --config ${{matrix.config}} --target integration_tests
