name: GCC

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CRADLE_THINKNODE_API_TOKEN: ${{ secrets.CRADLE_THINKNODE_API_TOKEN }}
  CRADLE_THINKNODE_DOCKER_AUTH: ${{ secrets.CRADLE_THINKNODE_DOCKER_AUTH }}

jobs:

  gcc:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.conan/data
        key: ${{runner.os}}-GCC-10-${{matrix.config}}

    - name: Install
      run: |
        sudo apt install lcov ocaml-nox
        sudo pip3 install virtualenv

    - name: Configure
      run: |
        export CC=`which gcc-10`
        export CXX=`which g++-10`
        ${CXX} --version
        scripts/set-up-python.sh --python=python3
        source .venv/bin/activate
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} \
           -DCRADLE_USE_CONAN=ON .

    - name: Build
      run: |
        cmake --build build --config ${{matrix.config}} -j4

    - name: Test
      run: |
        python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN
        cmake --build build --config ${{matrix.config}} --target all_unit_tests -j4
        source .venv/bin/activate
        pip3 install -e python
        cmake --build build --config ${{matrix.config}} --target integration_tests

    - name: Benchmarks
      if: ${{ matrix.config == 'Release' }}
      run: |
        cmake --build build --config Release --target benchmark_tests
      timeout-minutes: 20
