name: GCC

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:

  gcc:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
        key: ${{runner.os}}-gcc-${{matrix.config}}

    - name: Install
      run: |
        sudo apt install gcc-9 lcov ocaml-nox
        sudo pip3 install virtualenv

    - name: Configure
      run: |
        export CC=`which gcc-9`
        export CXX=`which g++-9`
        scripts/set-up-python.sh --python=python3
        source .venv/bin/activate
        scripts/set-up-conan.sh
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} .

    - name: Build & Test
      run: >
        python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN

        cmake --build build --config ${{matrix.config}}
        --target all_tests -j4
