name: MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CRADLE_THINKNODE_API_TOKEN: ${{ secrets.CRADLE_THINKNODE_API_TOKEN }}

jobs:

  preprocess:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.conan/data
        key: ${{runner.os}}-GCC-${{matrix.config}}

    - name: Install
      run: |
        sudo apt install lcov ocaml-nox
        sudo pip3 install virtualenv

    - name: Preprocess
      run: |
        gcc --version
        scripts/set-up-python.sh --python=python3
        source .venv/bin/activate
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Debug .
        cmake --build build --target preprocessing -j4

    - name: Upload preprocessed headers
      uses: actions/upload-artifact@v2
      with:
        name: preprocessed
        path: build/generated

  VS2019:
    runs-on: windows-latest
    needs: preprocess

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          C:/.conan/data
        key: ${{runner.os}}-MSVC-${{matrix.config}}

    - name: Install Conan
      run: |
        pip install conan

    - name: Download preprocessed headers
      uses: actions/download-artifact@v2
      with:
        name: preprocessed
        path: preprocessed

    - name: Configure
      run: >
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}}
        -DPREPROCESSOR_USAGE=External
        -DEXTERNALLY_PREPROCESSED_DIRECTORY=preprocessed
        -DLOCAL_DOCKER_TESTING=OFF

    - name: Build & Test
      run: >
        python python/generate_config.py $Env:CRADLE_THINKNODE_API_TOKEN

        cmake --build build --config ${{matrix.config}}
        --target unit_tests_target -j4
