name: MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CRADLE_THINKNODE_API_TOKEN: ${{ secrets.CRADLE_THINKNODE_API_TOKEN }}

jobs:

  VS2019:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          C:/.conan/data
        key: ${{runner.os}}-MSVC-${{matrix.config}}

    - name: Install OCaml
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-i686-ocaml

    - name: Update path
      run: |
        echo "c:\msys64\mingw32\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "c:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install Conan
      run: |
        pip install conan

    - name: Configure
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=${{matrix.config}} .

    - name: Build & Test
      run: >
        python python/generate_config.py $CRADLE_THINKNODE_API_TOKEN

        cmake --build build --config ${{matrix.config}}
        --target unit_tests_target -j4
