name: Release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Parse Tag
        id: parse-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/([0-9]+).[0-9]+.[0-9]+$ ]]; then
            echo "::set-output ${BASH_REMATCH[1]}"
          else
            echo "Version regex didn't match"
            false
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            mghro/cradle:latest-${{ steps.parse-tag.outputs.match }}.x
            mghro/cradle:${{ github.event.ref }}

      - name: Image Digest
        run: echo ${{ steps.docker-build.outputs.digest }}
